// Code generated by scripts/generate_builtins_man.sh — do not edit.
package main

// BuiltinManEntry holds documentation for a single builtin function.
type BuiltinManEntry struct {
	Sig     string
	Desc    string
	Example string
}

// builtinManDocs is the lookup table used by ez man <name>.
var builtinManDocs = map[string]BuiltinManEntry{
	"println":    {Sig: "println([value])", Desc: "Prints any value to stdout followed by a newline. Called with no args prints a blank line.", Example: "println(\"hello, world\")\nprintln(42)\nprintln(my_struct)\nprintln()"},
	"print":      {Sig: "print(value)", Desc: "Prints any value to stdout without a trailing newline.", Example: "print(\"loading... \")\nprint(42)"},
	"eprintln":   {Sig: "eprintln([value])", Desc: "Prints any value to stderr followed by a newline. Called with no args prints a blank line.", Example: "eprintln(\"error: something went wrong\")\neprintln()"},
	"eprint":     {Sig: "eprint(value)", Desc: "Prints any value to stderr without a trailing newline.", Example: "eprint(\"warning: \")\neprint(code)"},
	"input":      {Sig: "input() -> string", Desc: "Reads a line from stdin and returns it as a string (newline stripped).", Example: "print(\"Name: \")\nmut name string = input()\nprintln(\"Hello, ${name}\")"},
	"assert":     {Sig: "assert(condition bool, message string)", Desc: "Terminates the program if condition is false, printing the message and source location.", Example: "assert(x > 0, \"x must be positive\")\nassert(len(items) > 0, \"list cannot be empty\")"},
	"panic":      {Sig: "panic(message string)", Desc: "Immediately terminates the program with the given message and source location.", Example: "panic(\"unreachable code reached\")"},
	"exit":       {Sig: "exit(code int)", Desc: "Exits the program immediately with the given exit code.", Example: "exit(0)\nexit(1)"},
	"sleep_s":    {Sig: "sleep_s(seconds int)", Desc: "Pauses execution for the given number of seconds.", Example: "sleep_s(1)"},
	"sleep_ms":   {Sig: "sleep_ms(milliseconds int)", Desc: "Pauses execution for the given number of milliseconds.", Example: "sleep_ms(500)"},
	"sleep_ns":   {Sig: "sleep_ns(nanoseconds int)", Desc: "Pauses execution for the given number of nanoseconds.", Example: "sleep_ns(1000000)"},
	"int":        {Sig: "int(value) -> int", Desc: "Converts a value to int (64-bit signed). Truncates floats toward zero. char converts to codepoint.", Example: "mut x int = int(3.9)\nmut y int = int('A')"},
	"uint":       {Sig: "uint(value) -> uint", Desc: "Converts a value to uint (64-bit unsigned integer).", Example: "mut x uint = uint(42)"},
	"float":      {Sig: "float(value) -> float", Desc: "Converts a value to float (64-bit double). Integer promotion is lossless within range.", Example: "mut x float = float(42)"},
	"string":     {Sig: "string(value) -> string", Desc: "Converts any value to its string representation.", Example: "mut s string = string(123)\nmut s2 string = string(true)"},
	"char":       {Sig: "char(codepoint int) -> char", Desc: "Converts an integer Unicode codepoint to a char value.", Example: "mut c char = char(65)\nprintln(c)"},
	"byte":       {Sig: "byte(value) -> byte", Desc: "Converts a value to byte (uint8, 0-255).", Example: "mut b byte = byte(255)"},
	"bool":       {Sig: "bool(value) -> bool", Desc: "Converts a value to bool.", Example: "mut flag bool = true\nmut done bool = false"},
	"cast":       {Sig: "cast(value, TargetType) -> TargetType", Desc: "Explicit type conversion. Required for sized integer types (i8, u32, etc). Truncates floats. Enforces range at runtime.", Example: "mut x int = cast(3.7, int)\nmut b u8 = cast(200, u8)\nmut f float = cast(my_int, float)"},
	"i8":         {Sig: "i8", Desc: "8-bit signed integer type (-128 to 127). Declare with type annotation; convert with cast(value, i8).", Example: "mut x i8 = 100\nmut y i8 = cast(my_int, i8)"},
	"i16":        {Sig: "i16", Desc: "16-bit signed integer type (-32768 to 32767). Declare with type annotation; convert with cast(value, i16).", Example: "mut x i16 = 1000\nmut y i16 = cast(my_int, i16)"},
	"i32":        {Sig: "i32", Desc: "32-bit signed integer type. Declare with type annotation; convert with cast(value, i32).", Example: "mut x i32 = 100000\nmut y i32 = cast(my_int, i32)"},
	"i64":        {Sig: "i64", Desc: "64-bit signed integer type (same as int). Declare with type annotation; convert with cast(value, i64).", Example: "mut x i64 = 1000000000"},
	"u8":         {Sig: "u8", Desc: "8-bit unsigned integer type (0-255, same as byte). Declare with type annotation; convert with cast(value, u8).", Example: "mut x u8 = 200\nmut y u8 = cast(my_int, u8)"},
	"u16":        {Sig: "u16", Desc: "16-bit unsigned integer type (0-65535). Declare with type annotation; convert with cast(value, u16).", Example: "mut x u16 = 60000"},
	"u32":        {Sig: "u32", Desc: "32-bit unsigned integer type. Declare with type annotation; convert with cast(value, u32).", Example: "mut x u32 = 4000000000"},
	"u64":        {Sig: "u64", Desc: "64-bit unsigned integer type (same as uint). Declare with type annotation; convert with cast(value, u64).", Example: "mut x u64 = 18446744073709551615"},
	"f32":        {Sig: "f32", Desc: "32-bit float type. Declare with type annotation; convert with cast(value, f32).", Example: "mut x f32 = 3.14\nmut y f32 = cast(my_float, f32)"},
	"f64":        {Sig: "f64", Desc: "64-bit float type (same as float). Declare with type annotation; convert with cast(value, f64).", Example: "mut x f64 = 3.14"},
	"i128":       {Sig: "i128(value) -> i128", Desc: "128-bit signed integer. Supports all arithmetic and comparisons. Overflow panics at runtime.", Example: "mut a i128 = i128(99999999999999999999)\nmut b int = int(a)"},
	"u128":       {Sig: "u128(value) -> u128", Desc: "128-bit unsigned integer. Supports all arithmetic and comparisons. Overflow panics at runtime.", Example: "mut a u128 = u128(99999999999999999999)"},
	"i256":       {Sig: "i256(value) -> i256", Desc: "256-bit signed integer. Supports all arithmetic and comparisons. Overflow panics at runtime.", Example: "mut a i256 = i256(0)"},
	"u256":       {Sig: "u256(value) -> u256", Desc: "256-bit unsigned integer. Supports all arithmetic and comparisons. Overflow panics at runtime.", Example: "mut a u256 = u256(0)"},
	"len":        {Sig: "len(collection) -> int", Desc: "Returns the length of an array, map, or string. For strings returns byte length, not character count (use char_count for that).", Example: "println(len(\"hello\"))\nprintln(len(my_array))\nprintln(len(my_map))"},
	"type_of":    {Sig: "type_of(value) -> string", Desc: "Returns the EZ type name of any value as a string at runtime.", Example: "println(type_of(42))\nprintln(type_of(\"hi\"))\nprintln(type_of(my_struct))"},
	"size_of":    {Sig: "size_of(Type) -> int", Desc: "Returns the size in bytes of a type. int=8, float=8, bool=1, string=16.", Example: "println(size_of(int))\nprintln(size_of(MyStruct))"},
	"new":        {Sig: "new(Type) -> ^Type", Desc: "Allocates a zero-initialized struct on the heap and returns a pointer to it.", Example: "mut p = new(Point)\np.x = 10\np.y = 20"},
	"ref":        {Sig: "ref(variable) -> ref<T>", Desc: "Creates a transparent alias to a variable. Reads and writes through the alias affect the original. Also used to take a function reference.", Example: "mut x int = 10\nmut r = ref(x)\nr = 99\nprintln(x)"},
	"addr":       {Sig: "addr(variable) -> ^T", Desc: "Returns a pointer to the memory address of a variable.", Example: "mut x int = 10\nmut p ^int = addr(x)\nprintln(p^)"},
	"copy":       {Sig: "copy(value T) -> T", Desc: "Creates a deep copy of any value. Mutations to the copy do not affect the original.", Example: "mut arr2 = copy(arr)\narr2[0] = 99\nprintln(arr[0])\nmut m2 = copy(my_map)\nmut s2 = copy(my_struct)"},
	"error":      {Sig: "error(message string) -> Error", Desc: "Creates an Error value with the given message. Access the message via string interpolation.", Example: "mut err Error = error(\"file not found\")\nprintln(\"${err}\")"},
	"range":      {Sig: "range(start int, end int [, step int]) -> Range", Desc: "Returns a Range from start (inclusive) to end (exclusive). Optional step controls the increment (default 1). Step of 0 panics at runtime.", Example: "for i in range(0, 5) { println(i) }\nfor i in range(0, 10, 2) { println(i) }"},
	"c_string":   {Sig: "c_string(ptr ^u8) -> string", Desc: "Wraps a null-terminated C char* pointer as an EZ string. Only valid with values from C interop (import c\"header.h\").", Example: "import c\"mylib.h\"\nmut s string = c_string(mylib_get_name())"},
	"to_char":    {Sig: "to_char(s string, index int) -> int", Desc: "Returns the Unicode codepoint at character position index (not byte position) in a UTF-8 string. Panics if out of bounds.", Example: "mut cp int = to_char(\"hello\", 0)\nprintln(cp)"},
	"char_count": {Sig: "char_count(s string) -> int", Desc: "Returns the number of Unicode codepoints in a UTF-8 string. Unlike len() which counts bytes.", Example: "println(char_count(\"hello\"))\nprintln(len(\"hello\"))"},
	"here":       {Sig: "here() -> SourceLocation", Desc: "Returns a SourceLocation with the current file, line, and column filled in at compile time.", Example: "mut loc = here()\nprintln(loc.file)\nprintln(loc.line)"},
}
