// Code generated by scripts/generate_stdlib_man.sh — do not edit.
package main

// StdlibManEntry holds documentation for a single stdlib function.
type StdlibManEntry struct {
	Module  string
	Group   string
	Sig     string
	Desc    string
	Example string
}

// stdlibManDocs is the per-function lookup table used by ez man <name>.
var stdlibManDocs = map[string]StdlibManEntry{
	"abs":         {Module: "math", Group: "Arithmetic", Sig: "abs(n T) -> T", Desc: "Returns the absolute value of n. Works on int and float. Returns the same type as the input.", Example: "import @math\nprintln(math.abs(-5))\nprintln(math.abs(-3.14))"},
	"neg":         {Module: "math", Group: "Arithmetic", Sig: "neg(n T) -> T", Desc: "Returns the negation of n. Works on int and float. Returns the same type as the input.", Example: "import @math\nprintln(math.neg(5))\nprintln(math.neg(-3.14))"},
	"sign":        {Module: "math", Group: "Arithmetic", Sig: "sign(n int) -> int", Desc: "Returns -1 if n is negative, 0 if zero, or 1 if positive.", Example: "import @math\nprintln(math.sign(-7))\nprintln(math.sign(0))\nprintln(math.sign(3))"},
	"min":         {Module: "math", Group: "Min/Max/Clamp", Sig: "min(a T, b T) -> T", Desc: "Returns the smaller of two values. Works on int and float.", Example: "import @math\nprintln(math.min(3, 7))\nprintln(math.min(1.5, 2.5))"},
	"max":         {Module: "math", Group: "Min/Max/Clamp", Sig: "max(a T, b T) -> T", Desc: "Returns the larger of two values. Works on int and float.", Example: "import @math\nprintln(math.max(3, 7))\nprintln(math.max(1.5, 2.5))"},
	"clamp":       {Module: "math", Group: "Min/Max/Clamp", Sig: "clamp(value T, min T, max T) -> T", Desc: "Clamps value to the range [min, max]. Works on int and float.", Example: "import @math\nprintln(math.clamp(15, 1, 10))\nprintln(math.clamp(1.5, 0.0, 1.0))"},
	"floor":       {Module: "math", Group: "Rounding", Sig: "floor(n float) -> float", Desc: "Rounds n down to the nearest integer value, returned as float.", Example: "import @math\nprintln(math.floor(3.7))\nprintln(math.floor(-1.2))"},
	"ceil":        {Module: "math", Group: "Rounding", Sig: "ceil(n float) -> float", Desc: "Rounds n up to the nearest integer value, returned as float.", Example: "import @math\nprintln(math.ceil(3.2))\nprintln(math.ceil(-1.8))"},
	"round":       {Module: "math", Group: "Rounding", Sig: "round(n float) -> float", Desc: "Rounds n to the nearest integer (half rounds away from zero), returned as float.", Example: "import @math\nprintln(math.round(3.5))\nprintln(math.round(3.4))"},
	"trunc":       {Module: "math", Group: "Rounding", Sig: "trunc(n float) -> float", Desc: "Truncates n toward zero, returned as float.", Example: "import @math\nprintln(math.trunc(3.9))\nprintln(math.trunc(-3.9))"},
	"pow":         {Module: "math", Group: "Powers/Roots", Sig: "pow(base float, exp float) -> float", Desc: "Returns base raised to the power exp.", Example: "import @math\nprintln(math.pow(2.0, 10.0))"},
	"sqrt":        {Module: "math", Group: "Powers/Roots", Sig: "sqrt(n float) -> float", Desc: "Returns the square root of n. Panics at runtime if n is negative.", Example: "import @math\nprintln(math.sqrt(9.0))\nprintln(math.sqrt(2.0))"},
	"cbrt":        {Module: "math", Group: "Powers/Roots", Sig: "cbrt(n float) -> float", Desc: "Returns the cube root of n.", Example: "import @math\nprintln(math.cbrt(27.0))"},
	"hypot":       {Module: "math", Group: "Powers/Roots", Sig: "hypot(x float, y float) -> float", Desc: "Returns the hypotenuse of a right triangle with legs x and y (sqrt(x^2 + y^2)).", Example: "import @math\nprintln(math.hypot(3.0, 4.0))"},
	"exp":         {Module: "math", Group: "Powers/Roots", Sig: "exp(n float) -> float", Desc: "Returns e raised to the power n.", Example: "import @math\nprintln(math.exp(1.0))"},
	"exp2":        {Module: "math", Group: "Powers/Roots", Sig: "exp2(n float) -> float", Desc: "Returns 2 raised to the power n.", Example: "import @math\nprintln(math.exp2(8.0))"},
	"log":         {Module: "math", Group: "Logarithms", Sig: "log(n float) -> float", Desc: "Returns the natural (base-e) logarithm of n. Panics if n <= 0.", Example: "import @math\nprintln(math.log(math.E))"},
	"log2":        {Module: "math", Group: "Logarithms", Sig: "log2(n float) -> float", Desc: "Returns the base-2 logarithm of n. Panics if n <= 0.", Example: "import @math\nprintln(math.log2(8.0))"},
	"log10":       {Module: "math", Group: "Logarithms", Sig: "log10(n float) -> float", Desc: "Returns the base-10 logarithm of n. Panics if n <= 0.", Example: "import @math\nprintln(math.log10(100.0))"},
	"log_base":    {Module: "math", Group: "Logarithms", Sig: "log_base(value float, base float) -> float", Desc: "Returns the logarithm of value in the given base.", Example: "import @math\nprintln(math.log_base(8.0, 2.0))"},
	"sin":         {Module: "math", Group: "Trigonometry", Sig: "sin(rad float) -> float", Desc: "Returns the sine of an angle in radians.", Example: "import @math\nprintln(math.sin(math.PI / 2.0))"},
	"cos":         {Module: "math", Group: "Trigonometry", Sig: "cos(rad float) -> float", Desc: "Returns the cosine of an angle in radians.", Example: "import @math\nprintln(math.cos(0.0))"},
	"tan":         {Module: "math", Group: "Trigonometry", Sig: "tan(rad float) -> float", Desc: "Returns the tangent of an angle in radians.", Example: "import @math\nprintln(math.tan(math.PI / 4.0))"},
	"asin":        {Module: "math", Group: "Trigonometry", Sig: "asin(n float) -> float", Desc: "Returns the arc sine in radians. Panics if n is outside [-1, 1].", Example: "import @math\nprintln(math.asin(1.0))"},
	"acos":        {Module: "math", Group: "Trigonometry", Sig: "acos(n float) -> float", Desc: "Returns the arc cosine in radians. Panics if n is outside [-1, 1].", Example: "import @math\nprintln(math.acos(1.0))"},
	"atan":        {Module: "math", Group: "Trigonometry", Sig: "atan(n float) -> float", Desc: "Returns the arc tangent in radians.", Example: "import @math\nprintln(math.atan(1.0))"},
	"atan2":       {Module: "math", Group: "Trigonometry", Sig: "atan2(y float, x float) -> float", Desc: "Returns the arc tangent of y/x in radians, using the signs of both to determine quadrant.", Example: "import @math\nprintln(math.atan2(1.0, 1.0))"},
	"sinh":        {Module: "math", Group: "Trigonometry", Sig: "sinh(n float) -> float", Desc: "Returns the hyperbolic sine of n.", Example: "import @math\nprintln(math.sinh(1.0))"},
	"cosh":        {Module: "math", Group: "Trigonometry", Sig: "cosh(n float) -> float", Desc: "Returns the hyperbolic cosine of n.", Example: "import @math\nprintln(math.cosh(0.0))"},
	"tanh":        {Module: "math", Group: "Trigonometry", Sig: "tanh(n float) -> float", Desc: "Returns the hyperbolic tangent of n.", Example: "import @math\nprintln(math.tanh(1.0))"},
	"deg_to_rad":  {Module: "math", Group: "Trigonometry", Sig: "deg_to_rad(deg float) -> float", Desc: "Converts degrees to radians.", Example: "import @math\nprintln(math.deg_to_rad(180.0))"},
	"rad_to_deg":  {Module: "math", Group: "Trigonometry", Sig: "rad_to_deg(rad float) -> float", Desc: "Converts radians to degrees.", Example: "import @math\nprintln(math.rad_to_deg(math.PI))"},
	"is_even":     {Module: "math", Group: "Properties", Sig: "is_even(n int) -> bool", Desc: "Returns true if n is even.", Example: "import @math\nprintln(math.is_even(4))"},
	"is_odd":      {Module: "math", Group: "Properties", Sig: "is_odd(n int) -> bool", Desc: "Returns true if n is odd.", Example: "import @math\nprintln(math.is_odd(3))"},
	"is_infinite": {Module: "math", Group: "Properties", Sig: "is_infinite(n float) -> bool", Desc: "Returns true if n is positive or negative infinity.", Example: "import @math\nprintln(math.is_infinite(math.INF))"},
	"is_nan":      {Module: "math", Group: "Properties", Sig: "is_nan(n float) -> bool", Desc: "Returns true if n is NaN (Not a Number).", Example: "import @math\nmut nan_val float = math.INF - math.INF\nprintln(math.is_nan(nan_val))"},
	"is_finite":   {Module: "math", Group: "Properties", Sig: "is_finite(n float) -> bool", Desc: "Returns true if n is a finite number (not infinite or NaN).", Example: "import @math\nprintln(math.is_finite(3.14))"},
	"factorial":   {Module: "math", Group: "Statistical", Sig: "factorial(n int) -> int", Desc: "Returns n! (n factorial). n must be non-negative. Panics on negative input.", Example: "import @math\nprintln(math.factorial(5))"},
	"gcd":         {Module: "math", Group: "Statistical", Sig: "gcd(a int, b int) -> int", Desc: "Returns the greatest common divisor of a and b.", Example: "import @math\nprintln(math.gcd(12, 8))"},
	"lcm":         {Module: "math", Group: "Statistical", Sig: "lcm(a int, b int) -> int", Desc: "Returns the least common multiple of a and b.", Example: "import @math\nprintln(math.lcm(4, 6))"},
	"is_prime":    {Module: "math", Group: "Statistical", Sig: "is_prime(n int) -> bool", Desc: "Returns true if n is a prime number.", Example: "import @math\nprintln(math.is_prime(7))\nprintln(math.is_prime(9))"},
	"lerp":        {Module: "math", Group: "Utility", Sig: "lerp(a float, b float, t float) -> float", Desc: "Linearly interpolates between a and b by factor t. t=0 returns a, t=1 returns b.", Example: "import @math\nprintln(math.lerp(0.0, 10.0, 0.5))"},
	"distance":    {Module: "math", Group: "Utility", Sig: "distance(x1 float, y1 float, x2 float, y2 float) -> float", Desc: "Returns the Euclidean distance between two 2D points (x1, y1) and (x2, y2).", Example: "import @math\nprintln(math.distance(0.0, 0.0, 3.0, 4.0))"},
}

// stdlibModules maps module names to their ordered function lists.
var stdlibModules = map[string][]string{
	"math": {"abs", "neg", "sign", "min", "max", "clamp", "floor", "ceil", "round", "trunc", "pow", "sqrt", "cbrt", "hypot", "exp", "exp2", "log", "log2", "log10", "log_base", "sin", "cos", "tan", "asin", "acos", "atan", "atan2", "sinh", "cosh", "tanh", "deg_to_rad", "rad_to_deg", "is_even", "is_odd", "is_infinite", "is_nan", "is_finite", "factorial", "gcd", "lcm", "is_prime", "lerp", "distance"},
}

// stdlibGroup is one labeled group of names within a module index.
type stdlibGroup struct {
	Label string
	Names []string
}

// stdlibModuleGroups maps module names to their display groups.
var stdlibModuleGroups = map[string][]stdlibGroup{
	"math": {
		{Label: "Arithmetic    ", Names: []string{"abs", "neg", "sign"}},
		{Label: "Min/Max/Clamp ", Names: []string{"min", "max", "clamp"}},
		{Label: "Rounding      ", Names: []string{"floor", "ceil", "round", "trunc"}},
		{Label: "Powers/Roots  ", Names: []string{"pow", "sqrt", "cbrt", "hypot", "exp", "exp2"}},
		{Label: "Logarithms    ", Names: []string{"log", "log2", "log10", "log_base"}},
		{Label: "Trigonometry  ", Names: []string{"sin", "cos", "tan", "asin", "acos", "atan", "atan2", "sinh", "cosh", "tanh", "deg_to_rad", "rad_to_deg"}},
		{Label: "Properties    ", Names: []string{"is_even", "is_odd", "is_infinite", "is_nan", "is_finite"}},
		{Label: "Statistical   ", Names: []string{"factorial", "gcd", "lcm", "is_prime"}},
		{Label: "Utility       ", Names: []string{"lerp", "distance"}},
	},
}
