// Code generated by scripts/generate_stdlib_man.sh — do not edit.
package main

// StdlibManEntry holds documentation for a single stdlib function or type.
type StdlibManEntry struct {
	Module  string
	Group   string
	Kind    string // "func" or "type"
	Sig     string // for funcs: signature string
	Fields  string // for types: newline-separated "name\ttype" pairs
	Desc    string
	Example string
}

// stdlibManDocs is the per-function lookup table used by ez man <name>.
var stdlibManDocs = map[string]StdlibManEntry{
	"abs":         {Module: "math", Group: "Arithmetic", Kind: "func", Sig: "abs(n T) -> T", Fields: "", Desc: "Returns the absolute value of n. Works on int and float. Returns the same type as the input.", Example: ""},
	"neg":         {Module: "math", Group: "Arithmetic", Kind: "func", Sig: "neg(n T) -> T", Fields: "", Desc: "Returns the negation of n. Works on int and float. Returns the same type as the input.", Example: ""},
	"sign":        {Module: "math", Group: "Arithmetic", Kind: "func", Sig: "sign(n int) -> int", Fields: "", Desc: "Returns -1 if n is negative, 0 if zero, or 1 if positive.", Example: ""},
	"min":         {Module: "math", Group: "Min/Max/Clamp", Kind: "func", Sig: "min(a T, b T) -> T", Fields: "", Desc: "Returns the smaller of two values. Works on int and float.", Example: ""},
	"max":         {Module: "math", Group: "Min/Max/Clamp", Kind: "func", Sig: "max(a T, b T) -> T", Fields: "", Desc: "Returns the larger of two values. Works on int and float.", Example: ""},
	"clamp":       {Module: "math", Group: "Min/Max/Clamp", Kind: "func", Sig: "clamp(value T, min T, max T) -> T", Fields: "", Desc: "Clamps value to the range [min, max]. Works on int and float.", Example: ""},
	"floor":       {Module: "math", Group: "Rounding", Kind: "func", Sig: "floor(n float) -> float", Fields: "", Desc: "Rounds n down to the nearest integer value, returned as float.", Example: ""},
	"ceil":        {Module: "math", Group: "Rounding", Kind: "func", Sig: "ceil(n float) -> float", Fields: "", Desc: "Rounds n up to the nearest integer value, returned as float.", Example: ""},
	"round":       {Module: "math", Group: "Rounding", Kind: "func", Sig: "round(n float) -> float", Fields: "", Desc: "Rounds n to the nearest integer (half rounds away from zero), returned as float.", Example: ""},
	"trunc":       {Module: "math", Group: "Rounding", Kind: "func", Sig: "trunc(n float) -> float", Fields: "", Desc: "Truncates n toward zero, returned as float.", Example: ""},
	"pow":         {Module: "math", Group: "Powers/Roots", Kind: "func", Sig: "pow(base float, exp float) -> float", Fields: "", Desc: "Returns base raised to the power exp.", Example: ""},
	"sqrt":        {Module: "math", Group: "Powers/Roots", Kind: "func", Sig: "sqrt(n float) -> float", Fields: "", Desc: "Returns the square root of n. Panics at runtime if n is negative.", Example: ""},
	"cbrt":        {Module: "math", Group: "Powers/Roots", Kind: "func", Sig: "cbrt(n float) -> float", Fields: "", Desc: "Returns the cube root of n.", Example: ""},
	"hypot":       {Module: "math", Group: "Powers/Roots", Kind: "func", Sig: "hypot(x float, y float) -> float", Fields: "", Desc: "Returns the hypotenuse of a right triangle with legs x and y (sqrt(x^2 + y^2)).", Example: ""},
	"exp":         {Module: "math", Group: "Powers/Roots", Kind: "func", Sig: "exp(n float) -> float", Fields: "", Desc: "Returns e raised to the power n.", Example: ""},
	"exp2":        {Module: "math", Group: "Powers/Roots", Kind: "func", Sig: "exp2(n float) -> float", Fields: "", Desc: "Returns 2 raised to the power n.", Example: ""},
	"log":         {Module: "math", Group: "Logarithms", Kind: "func", Sig: "log(n float) -> float", Fields: "", Desc: "Returns the natural (base-e) logarithm of n. Panics if n <= 0.", Example: ""},
	"log2":        {Module: "math", Group: "Logarithms", Kind: "func", Sig: "log2(n float) -> float", Fields: "", Desc: "Returns the base-2 logarithm of n. Panics if n <= 0.", Example: ""},
	"log10":       {Module: "math", Group: "Logarithms", Kind: "func", Sig: "log10(n float) -> float", Fields: "", Desc: "Returns the base-10 logarithm of n. Panics if n <= 0.", Example: ""},
	"log_base":    {Module: "math", Group: "Logarithms", Kind: "func", Sig: "log_base(value float, base float) -> float", Fields: "", Desc: "Returns the logarithm of value in the given base.", Example: ""},
	"sin":         {Module: "math", Group: "Trigonometry", Kind: "func", Sig: "sin(rad float) -> float", Fields: "", Desc: "Returns the sine of an angle in radians.", Example: ""},
	"cos":         {Module: "math", Group: "Trigonometry", Kind: "func", Sig: "cos(rad float) -> float", Fields: "", Desc: "Returns the cosine of an angle in radians.", Example: ""},
	"tan":         {Module: "math", Group: "Trigonometry", Kind: "func", Sig: "tan(rad float) -> float", Fields: "", Desc: "Returns the tangent of an angle in radians.", Example: ""},
	"asin":        {Module: "math", Group: "Trigonometry", Kind: "func", Sig: "asin(n float) -> float", Fields: "", Desc: "Returns the arc sine in radians. Panics if n is outside [-1, 1].", Example: ""},
	"acos":        {Module: "math", Group: "Trigonometry", Kind: "func", Sig: "acos(n float) -> float", Fields: "", Desc: "Returns the arc cosine in radians. Panics if n is outside [-1, 1].", Example: ""},
	"atan":        {Module: "math", Group: "Trigonometry", Kind: "func", Sig: "atan(n float) -> float", Fields: "", Desc: "Returns the arc tangent in radians.", Example: ""},
	"atan2":       {Module: "math", Group: "Trigonometry", Kind: "func", Sig: "atan2(y float, x float) -> float", Fields: "", Desc: "Returns the arc tangent of y/x in radians, using the signs of both to determine quadrant.", Example: ""},
	"sinh":        {Module: "math", Group: "Trigonometry", Kind: "func", Sig: "sinh(n float) -> float", Fields: "", Desc: "Returns the hyperbolic sine of n.", Example: ""},
	"cosh":        {Module: "math", Group: "Trigonometry", Kind: "func", Sig: "cosh(n float) -> float", Fields: "", Desc: "Returns the hyperbolic cosine of n.", Example: ""},
	"tanh":        {Module: "math", Group: "Trigonometry", Kind: "func", Sig: "tanh(n float) -> float", Fields: "", Desc: "Returns the hyperbolic tangent of n.", Example: ""},
	"deg_to_rad":  {Module: "math", Group: "Trigonometry", Kind: "func", Sig: "deg_to_rad(deg float) -> float", Fields: "", Desc: "Converts degrees to radians.", Example: ""},
	"rad_to_deg":  {Module: "math", Group: "Trigonometry", Kind: "func", Sig: "rad_to_deg(rad float) -> float", Fields: "", Desc: "Converts radians to degrees.", Example: ""},
	"is_even":     {Module: "math", Group: "Properties", Kind: "func", Sig: "is_even(n int) -> bool", Fields: "", Desc: "Returns true if n is even.", Example: ""},
	"is_odd":      {Module: "math", Group: "Properties", Kind: "func", Sig: "is_odd(n int) -> bool", Fields: "", Desc: "Returns true if n is odd.", Example: ""},
	"is_infinite": {Module: "math", Group: "Properties", Kind: "func", Sig: "is_infinite(n float) -> bool", Fields: "", Desc: "Returns true if n is positive or negative infinity.", Example: ""},
	"is_nan":      {Module: "math", Group: "Properties", Kind: "func", Sig: "is_nan(n float) -> bool", Fields: "", Desc: "Returns true if n is NaN (Not a Number).", Example: ""},
	"is_finite":   {Module: "math", Group: "Properties", Kind: "func", Sig: "is_finite(n float) -> bool", Fields: "", Desc: "Returns true if n is a finite number (not infinite or NaN).", Example: ""},
	"factorial":   {Module: "math", Group: "Statistical", Kind: "func", Sig: "factorial(n int) -> int", Fields: "", Desc: "Returns n! (n factorial). n must be non-negative. Panics on negative input.", Example: ""},
	"gcd":         {Module: "math", Group: "Statistical", Kind: "func", Sig: "gcd(a int, b int) -> int", Fields: "", Desc: "Returns the greatest common divisor of a and b.", Example: ""},
	"lcm":         {Module: "math", Group: "Statistical", Kind: "func", Sig: "lcm(a int, b int) -> int", Fields: "", Desc: "Returns the least common multiple of a and b.", Example: ""},
	"is_prime":    {Module: "math", Group: "Statistical", Kind: "func", Sig: "is_prime(n int) -> bool", Fields: "", Desc: "Returns true if n is a prime number.", Example: ""},
	"lerp":        {Module: "math", Group: "Utility", Kind: "func", Sig: "lerp(a float, b float, t float) -> float", Fields: "", Desc: "Linearly interpolates between a and b by factor t. t=0 returns a, t=1 returns b.", Example: ""},
	"distance":    {Module: "math", Group: "Utility", Kind: "func", Sig: "distance(x1 float, y1 float, x2 float, y2 float) -> float", Fields: "", Desc: "Returns the Euclidean distance between two 2D points (x1, y1) and (x2, y2).", Example: ""},
	"to_upper":    {Module: "strings", Group: "Case", Kind: "func", Sig: "to_upper(s string) -> string", Fields: "", Desc: "Returns a copy of s with all ASCII letters converted to uppercase.", Example: ""},
	"to_lower":    {Module: "strings", Group: "Case", Kind: "func", Sig: "to_lower(s string) -> string", Fields: "", Desc: "Returns a copy of s with all ASCII letters converted to lowercase.", Example: ""},
	"trim":        {Module: "strings", Group: "Trim", Kind: "func", Sig: "trim(s string) -> string", Fields: "", Desc: "Returns a copy of s with leading and trailing whitespace removed.", Example: ""},
	"trim_left":   {Module: "strings", Group: "Trim", Kind: "func", Sig: "trim_left(s string) -> string", Fields: "", Desc: "Returns a copy of s with leading whitespace removed.", Example: ""},
	"trim_right":  {Module: "strings", Group: "Trim", Kind: "func", Sig: "trim_right(s string) -> string", Fields: "", Desc: "Returns a copy of s with trailing whitespace removed.", Example: ""},
	"contains":    {Module: "strings", Group: "Query", Kind: "func", Sig: "contains(s string, sub string) -> bool", Fields: "", Desc: "Returns true if s contains the substring sub.", Example: ""},
	"starts_with": {Module: "strings", Group: "Query", Kind: "func", Sig: "starts_with(s string, prefix string) -> bool", Fields: "", Desc: "Returns true if s starts with prefix.", Example: ""},
	"ends_with":   {Module: "strings", Group: "Query", Kind: "func", Sig: "ends_with(s string, suffix string) -> bool", Fields: "", Desc: "Returns true if s ends with suffix.", Example: ""},
	"index_of":    {Module: "strings", Group: "Query", Kind: "func", Sig: "index_of(s string, sub string) -> int", Fields: "", Desc: "Returns the byte index of the first occurrence of sub in s, or -1 if not found.", Example: ""},
	"count":       {Module: "strings", Group: "Query", Kind: "func", Sig: "count(s string, sub string) -> int", Fields: "", Desc: "Returns the number of non-overlapping occurrences of sub in s.", Example: ""},
	"is_empty":    {Module: "strings", Group: "Query", Kind: "func", Sig: "is_empty(s string) -> bool", Fields: "", Desc: "Returns true if s has zero length. Does not trim whitespace first.", Example: ""},
	"replace":     {Module: "strings", Group: "Transformation", Kind: "func", Sig: "replace(s string, old string, new string) -> string", Fields: "", Desc: "Returns a copy of s with all occurrences of old replaced by new.", Example: ""},
	"repeat":      {Module: "strings", Group: "Transformation", Kind: "func", Sig: "repeat(s string, count int) -> string", Fields: "", Desc: "Returns a string consisting of count copies of s concatenated together.", Example: ""},
	"reverse":     {Module: "strings", Group: "Transformation", Kind: "func", Sig: "reverse(s string) -> string", Fields: "", Desc: "Returns a copy of s with the bytes in reverse order.", Example: ""},
	"slice":       {Module: "strings", Group: "Transformation", Kind: "func", Sig: "slice(s string, start int, end int) -> string", Fields: "", Desc: "Returns the substring of s from byte index start (inclusive) to end (exclusive).", Example: ""},
	"split":       {Module: "strings", Group: "Split/Join", Kind: "func", Sig: "split(s string, sep string) -> [string]", Fields: "", Desc: "Splits s around each occurrence of sep and returns a string array.", Example: ""},
	"join":        {Module: "strings", Group: "Split/Join", Kind: "func", Sig: "join(arr [string], sep string) -> string", Fields: "", Desc: "Joins the elements of arr into a single string with sep between each element.", Example: ""},
}

// stdlibModules maps module names to their ordered function lists.
var stdlibModules = map[string][]string{
	"math":    {"abs", "neg", "sign", "min", "max", "clamp", "floor", "ceil", "round", "trunc", "pow", "sqrt", "cbrt", "hypot", "exp", "exp2", "log", "log2", "log10", "log_base", "sin", "cos", "tan", "asin", "acos", "atan", "atan2", "sinh", "cosh", "tanh", "deg_to_rad", "rad_to_deg", "is_even", "is_odd", "is_infinite", "is_nan", "is_finite", "factorial", "gcd", "lcm", "is_prime", "lerp", "distance"},
	"strings": {"to_upper", "to_lower", "trim", "trim_left", "trim_right", "contains", "starts_with", "ends_with", "index_of", "count", "is_empty", "replace", "repeat", "reverse", "slice", "split", "join"},
}

// stdlibGroup is one labeled group of names within a module index.
type stdlibGroup struct {
	Label string
	Names []string
}

// stdlibModuleGroups maps module names to their display groups.
var stdlibModuleGroups = map[string][]stdlibGroup{
	"math": {
		{Label: "Arithmetic    ", Names: []string{"abs", "neg", "sign"}},
		{Label: "Min/Max/Clamp ", Names: []string{"min", "max", "clamp"}},
		{Label: "Rounding      ", Names: []string{"floor", "ceil", "round", "trunc"}},
		{Label: "Powers/Roots  ", Names: []string{"pow", "sqrt", "cbrt", "hypot", "exp", "exp2"}},
		{Label: "Logarithms    ", Names: []string{"log", "log2", "log10", "log_base"}},
		{Label: "Trigonometry  ", Names: []string{"sin", "cos", "tan", "asin", "acos", "atan", "atan2", "sinh", "cosh", "tanh", "deg_to_rad", "rad_to_deg"}},
		{Label: "Properties    ", Names: []string{"is_even", "is_odd", "is_infinite", "is_nan", "is_finite"}},
		{Label: "Statistical   ", Names: []string{"factorial", "gcd", "lcm", "is_prime"}},
		{Label: "Utility       ", Names: []string{"lerp", "distance"}},
	},
	"strings": {
		{Label: "Case          ", Names: []string{"to_upper", "to_lower"}},
		{Label: "Trim          ", Names: []string{"trim", "trim_left", "trim_right"}},
		{Label: "Query         ", Names: []string{"contains", "starts_with", "ends_with", "index_of", "count", "is_empty"}},
		{Label: "Transformation", Names: []string{"replace", "repeat", "reverse", "slice"}},
		{Label: "Split/Join    ", Names: []string{"split", "join"}},
	},
}
