#!/usr/bin/env bash
#
# generate_builtins_man.sh — extract @man blocks from ez_builtins.h
# and generate cmd/ez/builtins_man_data.go
#
# Run from repo root or any subdirectory.
# Parallel to generate_errors.sh → error_codes.h → ERRORS.md pattern.

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(dirname "$SCRIPT_DIR")"
HEADER="$ROOT/ezc/src/stdlib/ez_builtins.h"
OUT="$ROOT/cmd/ez/builtins_man_data.go"

if [ ! -f "$HEADER" ]; then
    echo "generate_builtins_man.sh: error: $HEADER not found" >&2
    exit 1
fi

{
    echo "// Code generated by scripts/generate_builtins_man.sh — do not edit."
    echo "package main"
    echo ""
    echo "// BuiltinManEntry holds documentation for a single builtin function."
    echo "type BuiltinManEntry struct {"
    echo "	Sig     string"
    echo "	Desc    string"
    echo "	Example string"
    echo "}"
    echo ""
    echo "// builtinManDocs is the lookup table used by ez man <name>."
    echo "var builtinManDocs = map[string]BuiltinManEntry{"

    awk '
        /^\/\*@man / {
            name = substr($0, 8)
            gsub(/[[:space:]]/, "", name)
            in_block = 1; sig = ""; desc = ""; ex = ""; in_ex = 0
            next
        }
        in_block && /\*@sig /    { sig  = substr($0, index($0, "@sig ")  + 5); next }
        in_block && /\*@desc /   { desc = substr($0, index($0, "@desc ") + 6); next }
        in_block && /\*@example/ { in_ex = 1; next }
        in_block && /\*@end/     { in_ex = 0; next }
        in_block && in_ex {
            line = $0
            sub(/^ \*   /, "", line)
            gsub(/"/, "\\\"", line)
            ex = (ex == "" ? line : ex "\\n" line)
            next
        }
        in_block && /\*\// {
            gsub(/"/, "\\\"", sig)
            gsub(/"/, "\\\"", desc)
            printf "\t\"%s\": {Sig: \"%s\", Desc: \"%s\", Example: \"%s\"},\n", name, sig, desc, ex
            in_block = 0
            next
        }
    ' "$HEADER"

    echo "}"
} > "$OUT"

COUNT=$(grep -c '^\t"' "$OUT" || true)
echo "generate_builtins_man.sh: $COUNT entries written to $OUT"
